export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

export const GET_MOVIES_INIT = 'GET_MOVIES_INIT';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
