export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';

export const GET_MOVIES_INIT = 'GET_MOVIES_INIT';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';

export const ADD_FAVORITE_MOVIE = 'ADD_FAVORITE_MOVIE';
export const DELETE_FAVORITE_MOVIE = 'DELETE_FAVORITE_MOVIE';

export const GET_MOVIES_NEXT_PAGE_INIT = 'GET_MOVIES_NEXT_PAGE_INIT';
export const GET_MOVIES_NEXT_PAGE_SUCCESS = 'GET_MOVIES_NEXT_PAGE_SUCCESS';
export const GET_MOVIES_NEXT_PAGE_ERROR = 'GET_MOVIES_NEXT_PAGE_ERROR';

export const GET_MOVIE_DETAILS_INIT = 'GET_MOVIE_DETAILS_INIT';
export const GET_MOVIE_DETAILS_ERROR = 'GET_MOVIE_DETAILS_ERROR';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';

export const GET_ALL_MOVIES_DETAILS_INIT = 'GET_ALL_MOVIES_DETAILS_INIT';
export const GET_ALL_MOVIES_DETAILS_ERROR = 'GET_ALL_MOVIES_DETAILS_ERROR';
export const GET_ALL_MOVIES_DETAILS_SUCCESS = 'GET_ALL_MOVIES_DETAILS_SUCCESS';
